const categorias = {
  anime: [
    { titulo: "Demon Slayer", img: "images/anime/anime1.jpg", precio: 50 },
    { titulo: "Naruto", img: "images/anime/anime2.jpg", precio: 55 },
    { titulo: "Okami", img: "images/anime/anime3.jpg", precio: 80 },
    { titulo: "Dragon Ball", img: "images/anime/anime4.jpg", precio: 60 },
    { titulo: "Kito", img: "images/anime/anime5.jpg", precio: 75 },
    { titulo: "Evangelion", img: "images/anime/anime6.jpg", precio: 105 },
    { titulo: "Sailor Moon", img: "images/anime/anime7.jpg", precio: 70 },
    { titulo: "My Hero Academia", img: "images/anime/anime8.jpg", precio: 80 },
    { titulo: "Ranma 1/2", img: "images/anime/anime9.jpg", precio: 110 },
  ],
  comic: [
    { titulo: "Spiderman", img: "images/comic/comic1.jpg", precio: 60 },
    { titulo: "Spiderman", img: "images/comic/comic2.jpg", precio: 65 },
    { titulo: "Superman", img: "images/comic/comic3.jpg", precio: 80 },
    { titulo: "Superman", img: "images/comic/comic4.jpg", precio: 55 },
    { titulo: "Duende Verde", img: "images/comic/comic5.jpg", precio: 120 },
    { titulo: "Duende Verde", img: "images/comic/comic6.jpg", precio: 90 },
    { titulo: "Batman", img: "images/comic/comic7.jpg", precio: 65 },
    { titulo: "Batman", img: "images/comic/comic8.jpg", precio: 80 },
    { titulo: "Batman", img: "images/comic/comic9.jpg", precio: 65 },
  ],
  gaming: [
    { titulo: "Controller", img: "images/gaming/gaming1.jpg", precio: 110 },
    { titulo: "Super Mario", img: "images/gaming/gaming2.jpg", precio: 85 },
    { titulo: "Super Mario", img: "images/gaming/gaming3.jpg", precio: 200 },
    { titulo: "Nintendo", img: "images/gaming/gaming4.jpg", precio: 150 },
    { titulo: "Halo", img: "images/gaming/gaming5.jpg", precio: 110 },
    { titulo: "Final Fantasy", img: "images/gaming/gaming6.jpg", precio: 80 },
    { titulo: "Fallout", img: "images/gaming/gaming7.jpg", precio: 60 },
    { titulo: "Dark Souls", img: "images/gaming/gaming8.jpg", precio: 60 },
    { titulo: "Blizzard", img: "images/gaming/gaming9.jpg", precio: 95 },
  ],
  peliculas: [
    { titulo: "ET", img: "images/peli/peli1.jpg", precio: 250 },
    { titulo: "Halloween", img: "images/peli/peli2.jpg", precio: 120 },
    { titulo: "Scarface", img: "images/peli/peli3.jpg", precio: 325 },
    { titulo: "Casablanca", img: "images/peli/peli4.jpg", precio: 150 },
    { titulo: "Mad Max", img: "images/peli/peli5.jpg", precio: 95 },
    { titulo: "Mad Max", img: "images/peli/peli6.jpg", precio: 110 },
    { titulo: "Fight Club", img: "images/peli/peli7.jpg", precio: 200 },
    { titulo: "Terminator", img: "images/peli/peli8.jpg", precio: 230 },
    { titulo: "Fight Club", img: "images/peli/peli9.jpg", precio: 250 },
  ],
  series: [
    { titulo: "Juego de Tronos", img: "images/serie/serie1.jpg", precio: 120 },
    { titulo: "Juego de Tronos", img: "images/serie/serie2.jpg", precio: 95 },
    { titulo: "Dexter", img: "images/serie/serie3.jpg", precio: 150 },
    { titulo: "House", img: "images/serie/serie4.jpg", precio: 300 },
    {
      titulo: "Gangsters",
      img: "images/serie/serie5.jpg",
      precio: 90,
    },
    { titulo: "Dr. Jhon", img: "images/serie/serie6.jpg", precio: 130 },
    { titulo: "Breaking Bad", img: "images/serie/serie7.jpg", precio: 120 },
    { titulo: "Walking Dead", img: "images/serie/serie8.jpg", precio: 180 },
    { titulo: "The Office", img: "images/serie/serie9.jpg", precio: 220 },
  ],
};
